# Generated by Django 4.1.5 on 2023-01-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_complaint_spare_parts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-date_rejection'], 'verbose_name': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-shipping_date'], 'verbose_name': 'Машина'},
        ),
        migrations.AlterModelOptions(
            name='to',
            options={'ordering': ['-service_date'], 'verbose_name': '«ТО» (техническое обслуживание)'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='machine_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.machine', verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='to',
            name='company_make_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='to',
            name='machine_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.machine', verbose_name='Зав. № машины'),
        ),
    ]
